EXTRN INPUT:FAR
EXTRN RANKP:FAR
EXTRN OUTPUT:FAR
CODE SEGMENT
ASSUME CS:CODE
START:CALL FAR PTR INPUT
      CALL FAR PTR RANKP
      CALL FAR PTR OUTPUT
      MOV AH,4CH
      INT 21H
 CODE ENDS
      END START


