EXTRN RANK:WORD
EXTRN COUNT:WORD
PUBLIC OUTPUT

DATA SEGMENT PUBLIC
MESS2 DB 'RANK :$'
DATA  ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
OUTPUT PROC FAR
      MOV AX,DATA
      MOV DS,AX
      LEA DX,MESS2
      MOV AH,09H
      INT 21H
      MOV SI,0
      MOV DI,COUNT
 NEXT1:
      MOV BX,RANK[SI]
      CALL BINIDEC
      MOV DL,','
      MOV AH,02
      INT 21H
      ADD SI,2
      DEC DI
      JNZ NEXT1
      RET

BINIDEC PROC NEAR
     PUSH BX
     PUSH CX
    MOV CX,100
     CALL DEC_DIV
     MOV CX,10
     CALL DEC_DIV
     MOV CX,1
     CALL  DEC_DIV
     POP CX
     POP BX
     RET
BINIDEC ENDP

DEC_DIV PROC
   MOV  AX,BX
   MOV DX,0
   DIV CX
   MOV BX,DX
   MOV DL,AL
   ADD DL,30H
   MOV AH,02H
   INT 21H
   RET
DEC_DIV ENDP

OUTPUT ENDP
CODE ENDS
   END
